FROM --platform=linux/amd64 node:16-alpine
WORKDIR /usr/src/app

COPY package*.json ./
COPY *.ts .
COPY *.js .
COPY types .
COPY *.json .

RUN npm install
RUN npm run build


ARG SUPERTOKENS_CORE_URI
ARG SUPERTOKENS_API_KEY
ARG SMTP_HOST
ARG SMTP_USER
ARG SMTP_PASS
ARG SMTP_PORT
ARG SMTP_FROM_NAME
ARG SMTP_FROM_EMAIL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG APP_URL
ARG GRAPHQL_SERVER
ARG JWKS_CERT
ARG HASURA_ADMIN_SECRET

ENV SUPERTOKENS_CORE_URI=$SUPERTOKENS_CORE_URI
ENV SUPERTOKENS_API_KEY=$SUPERTOKENS_API_KEY
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_FROM_NAME=$SMTP_FROM_NAME
ENV SMTP_FROM_EMAIL=$SMTP_FROM_EMAIL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV APP_URL=$APP_URL
ENV PORT=9000
ENV GRAPHQL_SERVER=$GRAPHQL_SERVER
ENV JWKS_CERT=$JWKS_CERT
ENV HASURA_ADMIN_SECRET=$HASURA_ADMIN_SECRET

EXPOSE 9000
CMD [ "npm", "start" ]
